sudo: required
language: python
python:
  - "2.7"
install:
  - "pip install ansible"
script:
  - cd tests
  - ln -s ../../ users
  - ansible-playbook --connection=local --limit=localhost --inventory-file=hosts all.yml

