---
- name: Check user exists
  shell: /usr/bin/getent passwd "{{ item.username }}"|awk -F ":" '{print $1}'
  register: user_exist
  with_items: "{{ users }}"

- name: Deleted user removal
  user:
    name: "{{ item.username }}"
    state: absent
  with_items: "{{ users_deleted }}"
  tags: ['users','configuration']

- name: Deleted per-user group removal
  group:
    name: "{{ item.username }}"
    state: absent
  with_items: "{{ users_deleted }}"
  when: users_create_per_user_group
  tags: ['users','configuration']

- name: Creating groups
  group:
    name: "{{ item }}"
  when: item.uid is defined
  with_items: "{{ groups_to_create }}"
  tags: ['users','groups','configuration']

- name: Per-user group creation
  group:
    name: "{{ item.username }}"
    gid: "{{ item.uid }}"
  with_items: "{{ users }}"
  when: users_create_per_user_group and item.uid is defined
  tags: ['users','configuration']

- name: User creation
  user:
    name: "{{ item.username }}"
    group: "{{ users_create_per_user_group | ternary(item.username,users_group) }}"
    groups: "{{ item.groups | join(',') }}"
    shell: "{{ (item.shell is defined) | ternary(item.shell, users_default_shell) }}"
    password: "{{ item.password | default('!') }}"
    comment: "{{ item.name }}"
    uid: "{{ item.uid }}"
    createhome: "{{ users_create_homedirs | bool }}"
  when: item.stdout == ""
  with_items: "{{ user_exist.results }}"
  tags: ['users','configuration']

- name: User home directory creation and ssh-key push
  user:
    name: "{{ item.stdout }}"
    createhome: "{{ users_create_homedirs | bool }}"
  when: item.stdout != ""
  with_items: "{{ user_exist.results }}"
  tags: ['users','configuration']

- name: SSH keys
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - ssh_key
  tags: ['users','configuration']
